SNIFF = 'sniff'
LOOK = 'look'
NOTHING = 'nothing'
PLAY = 'play'
DIG = 'dig'
BARK = 'bark'
ROLL = 'rollover'
WALK = 'walk'
RUN = 'run'
STAND = 'stand'
FIND = 'find'
SLEEP = 'sleep'
SCRATCH = 'scratch'
FIGHT = 'fight'
INSIDE = 'inside'
BACK = 'back'
FORWARD = 'forward'
ITEMS = 'items'
ENTER = 'enter'
TRAIL = 'trail'
SWORD = 'sword'
SWIM = 'swim'
BOAT = 'boat'
DRINK = 'drink'
HEALTH = 'health'
ITEMS = 'items'
JUMP = 'jump'
CONTINUE = 'continue'
RETRIEVE = 'retrieve'
GATHER = 'gather'
SWIPE = 'swipe'
KICK = 'kick'
BITE = 'bite'
FIGHT = 'fight'
ATTACK = 'attack'
TUNNEL = 'tunnel'
QUIT = 'quit'
TOWEL = 'towel'
MEDPACK = 'medpack'
GIVE = 'give'
EAT = 'eat'
HEADLAMP = 'headlamp'
BALL = 'ball'
CHEW = 'chew'





        
